apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: http-set-resonse-body
  namespace: istio-system
spec:
  imagePullPolicy: Always
  # now this secert not work, set image privilege to public, when istio version >=1.14, this ok
  imagePullSecret: same-namespace-dockercfg-secert
  selector:
    matchLabels:
      app: istio-ingressgateway-xxx
      istio: ingressgateway
  url: oci://ccr.ccs.tencentyun.com/xxx/wasm:wasm-http-body-v0.0.1
  phase: AUTHN